version: "3"

services:
  magiconion:
    image: cysharp/magiconion_sample_chatapp_telemetry:4.3.1-1.0.0.rc4
    ports:
      - 5000:80
    environment:
      - DOTNET_ENVIRONMENT=Development
      - UseExporter=jaeger
      #- UseExporter=zipkin
      - Jaeger__AgentHost=jaeger
      - Zipkin__Endpoint=http://zipkin:9411/api/v2/spans
      - Server2ServerEndpoint=http://microserver:80
      - OTEL_LOG_LEVEL=debug
